version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./app/app:/app/app:rw
      - ./app/pyproject.toml:/app/pyproject.toml:ro
      - ./app/poetry.lock:/app/poetry.lock:ro
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - rabbitmq
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data:
